// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceMaster.Infrastructure;

#nullable disable

namespace PriceMaster.Infrastructure.Migrations
{
    [DbContext(typeof(PriceMasterDbContext))]
    [Migration("20260209194218_SeparateSeedingConfigs")]
    partial class SeparateSeedingConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("PriceMaster.Domain.Entities.BomItem", b =>
                {
                    b.Property<int>("BomItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("BomItemId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ProductId");

                    b.ToTable("BomItems", (string)null);
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Artifact"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "BaseMaterial"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "AssemblyWork"
                        });
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComponentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComponentName")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            ComponentId = 1,
                            CategoryId = 1,
                            ComponentName = "Button",
                            PricePerUnit = 5m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 2,
                            CategoryId = 1,
                            ComponentName = "Ring",
                            PricePerUnit = 5m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 3,
                            CategoryId = 1,
                            ComponentName = "Nail",
                            PricePerUnit = 5m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 4,
                            CategoryId = 1,
                            ComponentName = "Harness Component (simple)",
                            PricePerUnit = 10m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 5,
                            CategoryId = 1,
                            ComponentName = "Harness Component (stars)",
                            PricePerUnit = 20m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 6,
                            CategoryId = 1,
                            ComponentName = "Handle",
                            PricePerUnit = 50m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 50,
                            CategoryId = 1,
                            ComponentName = "Copper coin (n3)",
                            PricePerUnit = 5m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 51,
                            CategoryId = 1,
                            ComponentName = "Copper coin (n2)",
                            PricePerUnit = 10m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 52,
                            CategoryId = 1,
                            ComponentName = "Copper coin (n1)",
                            PricePerUnit = 20m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 53,
                            CategoryId = 1,
                            ComponentName = "Silver coin (copy)",
                            PricePerUnit = 72m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 90,
                            CategoryId = 1,
                            ComponentName = "Spherical ball",
                            PricePerUnit = 5m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 110,
                            CategoryId = 1,
                            ComponentName = "Inkwell",
                            PricePerUnit = 30m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 111,
                            CategoryId = 1,
                            ComponentName = "Tobacco pipe",
                            PricePerUnit = 25m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 120,
                            CategoryId = 1,
                            ComponentName = "Flint",
                            PricePerUnit = 80m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 500,
                            CategoryId = 2,
                            ComponentName = "Baguette 60*30",
                            PricePerUnit = 661m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 900,
                            CategoryId = 2,
                            ComponentName = "Printout 110",
                            PricePerUnit = 71m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 901,
                            CategoryId = 2,
                            ComponentName = "Printout 150",
                            PricePerUnit = 71m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 950,
                            CategoryId = 2,
                            ComponentName = "Hardware",
                            PricePerUnit = 25m,
                            UnitId = 1
                        },
                        new
                        {
                            ComponentId = 961,
                            CategoryId = 2,
                            ComponentName = "Textile, per sq.m.",
                            PricePerUnit = 150m,
                            UnitId = 2
                        },
                        new
                        {
                            ComponentId = 962,
                            CategoryId = 2,
                            ComponentName = "Polyurethane, per sq.m.",
                            PricePerUnit = 85m,
                            UnitId = 2
                        },
                        new
                        {
                            ComponentId = 1000,
                            CategoryId = 2,
                            ComponentName = "Work",
                            PricePerUnit = 800m,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecommendedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SizeHeight")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeWidth")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("SeriesId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.ProductionHistory", b =>
                {
                    b.Property<int>("ProductionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RecommendedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WorkCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductionHistoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionHistories", (string)null);
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId");

                    b.HasIndex("SeriesName")
                        .IsUnique();

                    b.ToTable("Series", (string)null);

                    b.HasData(
                        new
                        {
                            SeriesId = 1,
                            SeriesName = "Cossacks. Birth Of Liberty."
                        },
                        new
                        {
                            SeriesId = 2,
                            SeriesName = "UNR 1917-1921. The Ukrainian Liberation struggle."
                        },
                        new
                        {
                            SeriesId = 3,
                            SeriesName = "Kyivan Rus. The Golden Legacy."
                        });
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitName")
                        .IsUnique();

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            UnitName = "piece"
                        },
                        new
                        {
                            UnitId = 2,
                            UnitName = "sq.m"
                        });
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("PriceMaster.Domain.Entities.Component", "Component")
                        .WithMany("BomItems")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PriceMaster.Domain.Entities.Product", "Product")
                        .WithMany("BomItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Component", b =>
                {
                    b.HasOne("PriceMaster.Domain.Entities.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PriceMaster.Domain.Entities.Unit", "Unit")
                        .WithMany("Components")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Product", b =>
                {
                    b.HasOne("PriceMaster.Domain.Entities.Series", "Series")
                        .WithMany("Products")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.ProductionHistory", b =>
                {
                    b.HasOne("PriceMaster.Domain.Entities.Product", "Product")
                        .WithMany("ProductionHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Category", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Component", b =>
                {
                    b.Navigation("BomItems");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Product", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("ProductionHistories");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Series", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PriceMaster.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
